version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dernier-metro-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=metrodb
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: dernier-metro-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrodb
    ports:
      - "5432:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: