version: '3.8'

services:
  api:
    image: ghcr.io/thomassouly1409/dernier-metro-api:latest
    container_name: dernier-metro-api-staging
    environment:
      - NODE_ENV=staging
      - PORT=5000
      - PGHOST=postgres-staging
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=metrodb_staging
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres-staging
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metrodb_staging
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  pgdata_staging:
