name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: metro
          POSTGRES_PASSWORD: metro
          POSTGRES_DB: metrodb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U metro -d metrodb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PGHOST: localhost
      PGUSER: metro
      PGPASSWORD: metro
      PGDATABASE: metrodb
      PGPORT: 5432
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting 10s for PostgreSQL..."
          sleep 10

      - name: Initialize database
        run: psql -h localhost -U metro -d metrodb -f sql/init.sql

      - name: Run unit tests
        run: npm test

      - name: Run integration tests
        run: npm run test:integration
