name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: metro
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "⏳ Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Initialize DB
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d metro -c "
          CREATE TABLE IF NOT EXISTS config (
            key TEXT PRIMARY KEY,
            value JSONB
          );
          INSERT INTO config(key, value) VALUES
          ('metro.defaults', '{\"line\":\"M1\",\"tz\":\"Europe/Paris\"}'),
          ('metro.last', '{\"Chatelet\":\"01:30\",\"Bastille\":\"01:45\"}')
          ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
          "

      - name: Run tests
        run: npm test
