name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: metrodb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "⏳ Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Initialize DB
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d metrodb -c "
          CREATE TABLE IF NOT EXISTS config (
            key TEXT PRIMARY KEY,
            value JSONB
          );
          INSERT INTO config(key, value) VALUES
          ('metro.defaults', '{\"line\":\"M1\",\"tz\":\"Europe/Paris\"}'),
          ('metro.last', '{\"Chatelet\":\"01:30\",\"Bastille\":\"01:45\"}')
          ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
          "

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: metrodb 
          PGPORT: 5432
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dernier-metro-api:latest
            ghcr.io/${{ github.repository }}/dernier-metro-api:${{ github.sha }}
